export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    SELECT_CART_FROM_FIREBASE: 'SELECT_CART_FROM_FIREBASE',
    UPDATE_FIREBASE_CART:'UPDATE_FIREBASE_CART'
}